//#define NOW
#ifdef NOW
#include<stdio.h>
int count = 0;
int generate(int num) {
    if (num == 1) {
        ++count;
        printf("1\nNumber of hailstone generated:%d\n\n",count);
    }
    else
    {
        ++count;
        printf("%d ", num);
        if (num % 2) {
            generate(num * 3 + 1);
        }
        else {
            generate(num / 2);
        }
    }

}

int main(void) {
    int orinum;
    while (scanf("%d", &orinum) != EOF) {
        printf("Hailstone generated by %d:\n", orinum);
        generate(orinum);
        count = 0;
    }


    return 0;
}

#endif
